name: Build mod

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build mod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: |
            8
            17
            21
            25
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew -Dorg.gradle.java.installations.fromEnv=JAVA_HOME_8_X64,JAVA_HOME_17_X64,JAVA_HOME_21_X64,JAVA_HOME_25_X64 -Dorg.gradle.java.installations.auto-download=false -Pnet.minecraftforge.gradle.disableUpdateChecker=true build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StellarCore
          path: build/libs
